version: '3.3'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/bookapp-api
    env_file: .env
    ports:
      - '3001:3001'
      - '3002:3002'
    links:
      - mongodb
    depends_on: 
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    external: true
